### ISSUE TITLE
Why does this crate exist?

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bech32-bitcoin#38]
Why does this crate exist please? We have https://github.com/rust-bitcoin/rust-bech32 also within this GitHub organisation? @clarkmoody it looks like you started both of them, do you remember why?

**Comment by tcharding** [comment]
Ha ha, I just "found" this crate ... again and after wondering "what is this crate for" I saw this issue. @clarkmoody you just did a release 16 days ago, whats the purpose please so I don't tread on your toes?

**Comment by tcharding** [comment]
Ooooh this crate is meant to be a "Bitcoin" wrapper around `rust-bech32`? Is that implying that `rust-bech32` is _not_ a bitcoin specific crate? I still don't quite get the separation.

**Comment by clarkmoody** [comment]
Haha, yes. This crate adds the semantics of Witness Program version constraints and restricted HRP values on top of the bech32 encoding.

**Comment by tcharding** [comment]
No worries, at least in my mind, we should be able to do all that in the `rust-bech32`. Thanks.
