### ISSUE TITLE
Cleaning up the network constants

### ISSUE THREAD

**Issue by clarkmoody** [rust-bitcoin/rust-bech32-bitcoin#7]
The `Network` enum contains the human-readable constants for a few chains, and [there are more](https://github.com/satoshilabs/slips/blob/master/slip-0173.md) that are not included yet.

Since `Network` is a public enum, and new coins would be breaking changes, requiring a version bump.

There are a couple ways forward:
1. Break out `Network` into a new crate / repo, and link against an early version, not caring about newer coins.
2. Remove the concept entirely, leaving the `hrp` as a string input for the calling code.
3. Keep `Network`, but throw away all the coins except Bitcoin and Testnet. It's tough luck for other chains after this.

Thoughts?

**Comment by clarkmoody** [comment]
Note: I created a [placeholder repo](https://github.com/clarkmoody/rust-bech32-constants) to go down the 1. route above.

**Comment by sgeisler** [comment]
What do you think about rust-bitcoin/bitcoin-constants#1?

**Comment by clarkmoody** [comment]
@sgeisler It looks good so far. I guess we can add more fields as we go along: address prefixes, private key version bytes, etc.
